import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL=window.SUPABASE_URL||'YOUR_SUPABASE_URL', SUPABASE_ANON_KEY=window.SUPABASE_ANON_KEY||'YOUR_SUPABASE_ANON_KEY';
const supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY); const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function safe(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
async function init(){if(SUPABASE_URL.startsWith('YOUR_')){$('#loginMessage').textContent='Connect Supabase first; configuration is documented in README.md.';return}const {data:{session}}=await supabase.auth.getSession();if(session)showDashboard();}
function showDashboard(){$('#loginBox').hidden=true;$('#dashboard').hidden=false;loadContent();loadProjects();loadQuestions();loadDocs();}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});$('#loginMessage').textContent=error?error.message:'';if(!error)showDashboard();});
$('#signOut').onclick=async()=>{await supabase.auth.signOut();location.reload();};
$$('.adminnav button').forEach(b=>b.onclick=()=>{$$('.admin-tab').forEach(x=>x.hidden=true);$('#'+b.dataset.tab+'Tab').hidden=false;});
async function loadContent(){const {data}=await supabase.from('site_content').select('*').eq('id',1).maybeSingle();if(!data)return;Object.keys(data).forEach(k=>{const el=$(`#contentForm [name="${k}"]`);if(el)el.value=data[k]??'';});}
$('#contentForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const {error}=await supabase.from('site_content').upsert({id:1,...f});$('#contentMessage').textContent=error?error.message:'Saved.';});
async function loadProjects(){const {data}=await supabase.from('projects').select('*').order('sort_order');$('#projectList').innerHTML=(data||[]).map(p=>`<div class="row"><div><b>${safe(p.icon)} ${safe(p.title)}</b><p>${safe(p.description)}</p></div><button data-id="${p.id}" class="del-project">Delete</button></div>`).join('')||'<p class="muted">No projects yet.</p>';$$('.del-project').forEach(b=>b.onclick=async()=>{await supabase.from('projects').delete().eq('id',b.dataset.id);loadProjects();});}
$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));await supabase.from('projects').insert({...f,sort_order:Number(f.sort_order),published:true});e.target.reset();loadProjects();});
async function loadQuestions(){const {data}=await supabase.from('questions').select('*').order('created_at',{ascending:false});$('#questionList').innerHTML=(data||[]).map(q=>`<div class="row"><div><b>${safe(q.type)} · ${safe(q.name)}</b><p>${safe(q.body)}</p><small>${safe(q.email)}</small><p><input id="a-${q.id}" value="${safe(q.answer||'')}" placeholder="Optional response"></p></div><div><button data-id="${q.id}" class="pub">${q.published?'Unpublish':'Publish'}</button> <button data-id="${q.id}" class="delq">Delete</button></div></div>`).join('')||'<p class="muted">No submissions.</p>';$$('.pub').forEach(b=>b.onclick=async()=>{const q=data.find(x=>x.id==b.dataset.id);await supabase.from('questions').update({published:!q.published,answer:document.querySelector('#a-'+q.id).value}).eq('id',q.id);loadQuestions();});$$('.delq').forEach(b=>b.onclick=async()=>{await supabase.from('questions').delete().eq('id',b.dataset.id);loadQuestions();});}
async function loadDocs(){const {data}=await supabase.from('documents').select('*').order('created_at',{ascending:false});$('#documentList').innerHTML=(data||[]).map(d=>`<div class="row"><div><b>${safe(d.title)}</b><br><a href="${safe(d.url)}" target="_blank">${safe(d.url)}</a></div><button data-id="${d.id}" class="deldoc">Delete</button></div>`).join('')||'<p class="muted">No documents.</p>';$$('.deldoc').forEach(b=>b.onclick=async()=>{await supabase.from('documents').delete().eq('id',b.dataset.id);loadDocs();});}
$('#documentForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));await supabase.from('documents').insert({...f,published:true});e.target.reset();loadDocs();});
init();
