import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const URL=window.SUPABASE_URL||'',KEY=window.SUPABASE_ANON_KEY||'',db=createClient(URL,KEY),$=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function verifyAdmin(user){const {data,error}=await db.rpc('is_admin');if(error||data!==true){await db.auth.signOut();$('#loginMessage').className='admin-error';$('#loginMessage').textContent='This account is not authorised to administer the website.';return false}return true}
async function init(){const {data:{session}}=await db.auth.getSession();if(session&&await verifyAdmin(session.user))showDashboard()}
async function showDashboard(){$('#loginBox').hidden=true;$('#dashboard').hidden=false;$('#adminSecurity').textContent='✓ Signed in as an authorised website administrator.';await Promise.all([loadContent(),loadProjects(),loadQuestions(),loadDocs()])}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),m=$('#loginMessage');m.textContent='Signing in…';const {data,error}=await db.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error){m.textContent=error.message;return}if(await verifyAdmin(data.user))showDashboard()});$('#signOut').onclick=async()=>{await db.auth.signOut();location.reload()};$$('.adminnav button').forEach(b=>b.onclick=()=>{$$('.admin-tab').forEach(x=>x.hidden=true);$$('.adminnav button').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab+'Tab').hidden=false;b.classList.add('active')});
async function loadContent(){const {data}=await db.from('site_content').select('*').eq('id',1).maybeSingle();if(!data)return;Object.entries(data).forEach(([k,v])=>{const el=$(`#contentForm [name="${k}"]`);if(el)el.value=v??''})}$('#contentForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),m=$('#contentMessage');const {error}=await db.from('site_content').upsert({id:1,...f});m.textContent=error?error.message:'Saved. The public website will show the new information immediately.'});
async function loadProjects(){const {data}=await db.from('projects').select('*').order('sort_order');$('#projectList').innerHTML=(data||[]).map(p=>`<div class="row"><div><b>${safe(p.icon||'🌊')} ${safe(p.title)}</b><p>${safe(p.description)}</p></div><div class="row-actions"><button class="btn danger del-project" data-id="${p.id}">Delete</button></div></div>`).join('')||'<p class="muted">No projects yet.</p>';$$('.del-project').forEach(b=>b.onclick=async()=>{if(confirm('Delete this project?')){await db.from('projects').delete().eq('id',b.dataset.id);loadProjects()}})}$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));await db.from('projects').insert({...f,sort_order:Number(f.sort_order),published:true});e.target.reset();loadProjects()});
async function loadQuestions(){const {data}=await db.from('questions').select('*').order('created_at',{ascending:false});$('#questionList').innerHTML=(data||[]).map(q=>`<div class="row"><div><b>${safe(q.type)} · ${safe(q.name)}</b><p>${safe(q.body)}</p><small>Private email: ${safe(q.email)}</small><p><input id="a-${q.id}" value="${safe(q.answer||'')}" placeholder="Write a public response (optional)" style="width:100%;padding:9px"></p></div><div class="row-actions"><button class="btn secondary pub" data-id="${q.id}">${q.published?'Unpublish':'Publish'}</button><button class="btn danger delq" data-id="${q.id}">Delete</button></div></div>`).join('')||'<p class="muted">No resident messages.</p>';$$('.pub').forEach(b=>b.onclick=async()=>{const q=data.find(x=>x.id===b.dataset.id);await db.from('questions').update({published:!q.published,answer:$('#a-'+q.id).value}).eq('id',q.id);loadQuestions()});$$('.delq').forEach(b=>b.onclick=async()=>{if(confirm('Permanently delete this message?')){await db.from('questions').delete().eq('id',b.dataset.id);loadQuestions()}})}
async function loadDocs(){const {data}=await db.from('documents').select('*').order('created_at',{ascending:false});$('#documentList').innerHTML=(data||[]).map(d=>`<div class="row"><div><b>${safe(d.title)}</b><br><a href="${safe(d.url)}" target="_blank" rel="noopener">Open document</a></div><button class="btn danger deldoc" data-id="${d.id}">Delete</button></div>`).join('')||'<p class="muted">No documents yet.</p>';$$('.deldoc').forEach(b=>b.onclick=async()=>{if(confirm('Delete this document link?')){await db.from('documents').delete().eq('id',b.dataset.id);loadDocs()}})}$('#documentForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));await db.from('documents').insert({...f,published:true});e.target.reset();loadDocs()});init();