import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const URL=window.SUPABASE_URL||''; const KEY=window.SUPABASE_ANON_KEY||''; const db=URL&&KEY?createClient(URL,KEY):null;
const $=s=>document.querySelector(s); const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const statusInfo=p=>{const raw=(p.status||'').toLowerCase();if(raw.includes('complete'))return['Completed','completed'];if(raw.includes('delay')||raw.includes('pause'))return['Delayed / paused','delayed'];if(raw.includes('progress')||raw.includes('fund'))return['In progress','progress'];return['Under investigation','investigation']};
async function load(){ $('#year').textContent=new Date().getFullYear(); if(!db){fallback();return}
 const {data:c}=await db.from('site_content').select('*').eq('id',1).maybeSingle(); if(c){$('#status').textContent=c.status||'Updates ongoing';$('#updated').textContent=c.updated||'—';$('#focus').textContent=c.focus||'—';$('#intro').textContent=c.intro||$('#intro').textContent;$('#latest').textContent=c.latest||'Further updates will appear here.'}
 const {data:ps}=await db.from('projects').select('*').eq('published',true).order('sort_order'); $('#projectsGrid').innerHTML=(ps||[]).map(p=>{const [label,cls]=statusInfo(p);return `<article class="project-card"><div class="project-top"><span class="project-icon">${safe(p.icon||'🌊')}</span><span class="status-pill"><i class="dot ${cls}"></i> ${label}</span></div><h3>${safe(p.title)}</h3><p>${safe(p.description)}</p><div class="project-meta">View project position</div></article>`}).join('')||'<p class="muted">Project information is being prepared.</p>';
 const {data:docs}=await db.from('documents').select('*').eq('published',true).order('created_at',{ascending:false}).limit(4); $('#documents').innerHTML=(docs||[]).map(d=>`<p><a href="${safe(d.url)}" target="_blank" rel="noopener">${safe(d.title)} →</a></p>`).join('')||'<p class="muted">Document links will be added here.</p>';
 const {data:qs}=await db.from('questions').select('id,name,type,body,answer,created_at').eq('published',true).order('created_at',{ascending:false}).limit(6); $('#published').innerHTML=(qs||[]).map(q=>`<article class="question-card"><small>${safe(q.type)} · ${safe(q.name)}</small><p>${safe(q.body)}</p>${q.answer?`<p class="answer"><b>Response:</b> ${safe(q.answer)}</p>`:''}</article>`).join('')||'<p class="muted">Published community questions will appear here.</p>';
}
function fallback(){$('#status').textContent='Works and investigations ongoing';$('#updated').textContent='August 2026';$('#focus').textContent='Natural Flood Management and drainage investigations';$('#latest').textContent='Project information will be updated here.';$('#projectsGrid').innerHTML='<article class="project-card"><div class="project-top"><span class="project-icon">🌿</span><span class="status-pill"><i class="dot progress"></i> In progress</span></div><h3>The Slade</h3><p>Natural Flood Management measures intended to slow and hold back water.</p></article><article class="project-card"><div class="project-top"><span class="project-icon">🚧</span><span class="status-pill"><i class="dot investigation"></i> Under investigation</span></div><h3>Courtington Lane / Workhouse Lane</h3><p>Drainage options and downstream impacts are being investigated.</p></article>';$('#documents').innerHTML='<p class="muted">Documents will appear here.</p>';$('#published').innerHTML='<p class="muted">Published community questions will appear here.</p>'}
const form=$('#questionForm');form?.addEventListener('submit',async e=>{e.preventDefault();const msg=$('#formMessage');if(!db){msg.textContent='Submissions are temporarily unavailable.';return}const f=new FormData(form);msg.textContent='Sending…';const {error}=await db.from('questions').insert({name:f.get('name'),email:f.get('email'),type:f.get('type'),body:f.get('body'),published:false});msg.textContent=error?'Sorry — your message could not be sent. Please try again.':'Thank you. Your message has been sent for moderation.';if(!error)form.reset()});
$('.menu')?.addEventListener('click',()=>{const n=$('.nav nav');n.style.display=n.style.display==='flex'?'none':'flex';n.style.position='absolute';n.style.top='76px';n.style.left='0';n.style.right='0';n.style.padding='18px 5%';n.style.background='#0c2e39';n.style.flexDirection='column'});
load();