import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const URL=window.SUPABASE_URL||''; const KEY=window.SUPABASE_ANON_KEY||''; const db=URL&&KEY?createClient(URL,KEY):null;
const $=s=>document.querySelector(s); const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const statusInfo=p=>{const raw=(p.status||'').toLowerCase();if(raw.includes('complete'))return['Completed','completed'];if(raw.includes('delay')||raw.includes('pause'))return['Delayed / paused','delayed'];if(raw.includes('progress')||raw.includes('fund'))return['In progress','progress'];return['Under investigation','investigation']};
async function load(){ $('#year').textContent=new Date().getFullYear(); if(!db){fallback();return}
 const {data:c}=await db.from('site_content').select('*').eq('id',1).maybeSingle(); if(c){$('#status').textContent=c.status||'Works and investigations ongoing';$('#updated').textContent=c.updated||'September 2026';$('#focus').textContent=c.focus||'Natural Flood Management and drainage investigations';if(c.intro)$('#intro').textContent=c.intro;if(c.latest)$('#latest').textContent=c.latest;}
 const {data:ps}=await db.from('projects').select('*').eq('published',true).order('sort_order'); if(ps?.length){$('#projectsGrid').innerHTML=ps.map(p=>{const [label,cls]=statusInfo(p);return `<article class="project-card"><div class="project-top"><span class="project-icon">${safe(p.icon||'🌊')}</span><span class="status-pill"><i class="dot ${cls}"></i> ${label}</span></div><h3>${safe(p.title)}</h3><p>${safe(p.description)}</p><div class="project-meta">Bloxham flood programme</div></article>`}).join('')} else renderBloxhamProjects();
 const {data:docs}=await db.from('documents').select('*').eq('published',true).order('created_at',{ascending:false}).limit(4); $('#documents').innerHTML=(docs||[]).map(d=>`<p><a href="${safe(d.url)}" target="_blank" rel="noopener">${safe(d.title)} →</a></p>`).join('')||'<p><a href="https://www.bloxhamparishcouncil.gov.uk/flooding.php" target="_blank" rel="noopener">Bloxham flooding documents →</a></p>';
 const {data:qs}=await db.from('questions').select('id,name,type,body,answer,created_at').eq('published',true).order('created_at',{ascending:false}).limit(6); $('#published').innerHTML=(qs||[]).map(q=>`<article class="question-card"><small>${safe(q.type)} · ${safe(q.name)}</small><p>${safe(q.body)}</p>${q.answer?`<p class="answer"><b>Response:</b> ${safe(q.answer)}</p>`:''}</article>`).join('')||'<p class="muted">Published community questions will appear here.</p>';
}
function renderBloxhamProjects(){const projects=[
 ['🌿','The Slade','In progress','progress','Natural Flood Management is a current focus here. The aim is to slow and temporarily hold back water before it reaches more vulnerable parts of the village.'],
 ['🚧','Courtington Lane / Workhouse Lane','Under investigation','investigation','Drainage proposals and possible downstream impacts have been reviewed. Alternative approaches remain part of the local flood-alleviation discussion.'],
 ['🗺️','Wider NFM opportunities','Under investigation','investigation','Catchment mapping has been used to identify additional opportunities around Bloxham where land-based measures may slow runoff and spread or store water.'],
 ['🌊','Bloxham Brook & channel maintenance','Ongoing','progress','The brook, bridges and channel capacity are part of the wider flood picture. Local maintenance and evidence from the Section 19 investigation help inform priorities.'],
 ['🌾','Landowner engagement','Ongoing','progress','Natural Flood Management depends on practical locations and landowner agreement. Discussions with farmers and landowners are therefore a key part of turning mapped opportunities into deliverable schemes.'],
 ['🏠','Property resilience & emergency planning','Ongoing','progress','Community resilience remains important because flood-alleviation measures reduce risk but cannot remove it entirely. Local emergency planning and property-level protection form part of the response.']
];$('#projectsGrid').innerHTML=projects.map(p=>`<article class="project-card"><div class="project-top"><span class="project-icon">${p[0]}</span><span class="status-pill"><i class="dot ${p[3]}"></i> ${p[2]}</span></div><h3>${p[1]}</h3><p>${p[4]}</p><div class="project-meta">Bloxham flood programme</div></article>`).join('')}
function fallback(){$('#status').textContent='Works and investigations ongoing';$('#updated').textContent='September 2026';$('#focus').textContent='The Slade, wider NFM opportunities and drainage investigations';$('#latest').textContent='Bloxham now has a growing evidence base including the Oxfordshire County Council Section 19 investigation, Flooding Working Group updates and the Natural Flood Management report published in June 2026. The next challenge is converting identified opportunities into agreed, funded and deliverable measures while continuing work on drainage and local resilience.';renderBloxhamProjects();$('#documents').innerHTML='<p><a href="https://www.bloxhamparishcouncil.gov.uk/flooding.php" target="_blank" rel="noopener">Bloxham flooding documents →</a></p>';$('#published').innerHTML='<p class="muted">Published community questions will appear here.</p>'}
const form=$('#questionForm');form?.addEventListener('submit',async e=>{e.preventDefault();const msg=$('#formMessage');if(!db){msg.textContent='Submissions are temporarily unavailable.';return}const f=new FormData(form);msg.textContent='Sending…';const {error}=await db.from('questions').insert({name:f.get('name'),email:f.get('email'),type:f.get('type'),body:f.get('body'),published:false});msg.textContent=error?'Sorry — your message could not be sent. Please try again.':'Thank you. Your message has been sent for moderation.';if(!error)form.reset()});
$('.menu')?.addEventListener('click',()=>{const n=$('.nav nav');n.style.display=n.style.display==='flex'?'none':'flex';n.style.position='absolute';n.style.top='76px';n.style.left='0';n.style.right='0';n.style.padding='18px 5%';n.style.background='#0c2e39';n.style.flexDirection='column'});
load();