import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const URL=window.SUPABASE_URL||''; const KEY=window.SUPABASE_ANON_KEY||''; const db=URL&&KEY?createClient(URL,KEY):null;
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s); const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const statusInfo=p=>{const raw=(p.status||'').toLowerCase();if(raw.includes('complete'))return['Completed','completed'];if(raw.includes('delay')||raw.includes('pause'))return['Delayed / paused','delayed'];if(raw.includes('progress')||raw.includes('fund'))return['In progress','progress'];return['Under investigation','investigation']};

const programme=[
 {title:'The Slade Natural Flood Management',status:'In progress',cls:'progress',lead:'Bloxham Parish Council / Flooding Working Group, with OCC and catchment partners',funding:'Oxfordshire County Council grant approved. February 2026 working estimate: £8,919, to be refined against final design and actual costs.',latest:'August 2026: grant funding was expected shortly; Councillor Neil Hegarty was coordinating installation of leaky dams intended to hold back and spread water during high-flow events.',dates:['19 Nov 2025 — partner walk-through informed the outline scope','Feb 2026 — expression of interest and initial £8,919 estimate','Jul 2026 — OCC grant approval reported','Aug 2026 — installation planning / grant receipt progressing']},
 {title:'Courtington Lane / Workhouse Lane drainage',status:'Paused / alternatives under investigation',cls:'delayed',lead:'Oxfordshire County Council and Cherwell District Council, with Bloxham Parish Council and Bloxham School involvement',funding:'Cherwell District Council had agreed to cover the recommended work; May 2026 tenders were over budget and further funding was investigated.',latest:'August 2026: the planned drain-line works beneath the Bloxham School car park remained paused while OCC and CDC investigated alternatives, following concern that the scheme could increase flood risk elsewhere.',dates:['Jan 2025 — survey identified capacity reduction from 375 mm to 150 mm','Jul 2025 — Section 19 report published','Aug 2025 — dedicated local update issued','Mar 2026 — work then expected during school summer holiday','May 2026 — tenders over budget; further funding sought','Jul–Aug 2026 — original scheme paused; alternatives investigated']},
 {title:'Wider catchment NFM — west of Bloxham',status:'Design / funding development',cls:'investigation',lead:'Thames21, Oxfordshire County Council, Cherwell & Ray Catchment Partnership, farmer-cluster partners, landowners and Bloxham Community Flood Group',funding:'Report recommends Countryside Stewardship / Higher Tier and emerging private environmental investment, including possible water-company investment. Capital funding is still required for most wider interventions.',latest:'The April 2026 feasibility study identified about 3,535 m³ of potential temporary storage across five land groups, covering about 25% of the upstream catchment. Groups 1, 2 and 4 were recommended as priorities.',dates:['26 Mar 2025 — first multi-partner NFM discussion','9 Dec 2025 — wet-weather site survey','17 Apr 2026 — feasibility report issued','Jun 2026 — report published publicly','Next — RIBA Stage 2 outline design, funding and phased delivery']},
 {title:'Village drains and highway drainage',status:'Ongoing maintenance',cls:'progress',lead:'Oxfordshire County Council / Cherwell District Council, supported by Parish Council reporting',funding:'Highway/drain maintenance budgets; individual clearance works commissioned by the responsible authorities.',latest:'Drain clearance has reduced known blockages, but residents are still encouraged to report blocked gullies promptly through FixMyStreet because maintenance remains part of the flood-risk picture.',dates:['Early 2025 — widespread blocked-drain issues investigated','Spring 2025 — four-day DrainLine clearance programme across Tadmarton Road, Courtington Lane, High Street, Colesbourne Road and Brookside Way','2026 — continuing monitoring and reactive clearance']},
 {title:'Bloxham Brook / Little Bridge Road',status:'Monitoring and local maintenance',cls:'investigation',lead:'Environment Agency for main-river matters, with local authorities / riparian interests as applicable',funding:'Routine maintenance and local-authority / agency responsibilities; no separate major capital scheme confirmed on this site.',latest:'The Environment Agency walk-through found the brook generally clear apart from a minor silt build-up near Little Bridge Road. The core issue during Storm Bert was the volume of water exceeding channel and bridge capacity.',dates:['Spring 2025 — EA walk-through of Bloxham Brook','Jul 2025 — silt bank near Little Bridge Road cleared; Parish Council minutes reported water level dropping by about one inch','Ongoing — river-level monitoring and incident reporting']}
];

const milestones=[
 ['22–24 Nov 2024','Storm Bert','Severe fluvial and surface-water flooding. Official reporting captured up to 35 flooded properties, while wider community information suggests roughly 65 properties were affected; the exact number is unknown. At least five vehicles were badly affected.'],
 ['Jan 2025','Workhouse Lane drainage survey','Survey work found that flooding was not simply a blocked culvert issue and identified a reduction in drainage capacity from 375 mm to 150 mm.'],
 ['26 Mar 2025','NFM partnership begins','Bloxham representatives met BBOWT / catchment, Thames21, Natural England / farmer-cluster and Environment Agency partners to develop a Slow the Flow approach.'],
 ['Spring 2025','Village drain clearance','A four-day clearance and jetting programme covered key roads including Tadmarton Road, Courtington Lane and High Street.'],
 ['4 Jul 2025','Section 19 investigation published','Oxfordshire County Council published its formal investigation into the November 2024 flooding and allocated recommended actions.'],
 ['9 Dec 2025','NFM site survey','Thames21, Natural England and Cherwell & Ray Catchment Partnership representatives ground-truthed modelled runoff routes following sustained rainfall.'],
 ['17 Apr 2026','Bloxham NFM feasibility report issued','The report identified approximately 3,535 m³ of temporary storage opportunities across five land groups west of the village.'],
 ['Jun 2026','NFM report published','The Parish Council published the Bloxham Natural Flood Management report for residents.'],
 ['Jul 2026','The Slade grant approved','Parish Council reporting said Oxfordshire County Council had approved grant funding for Natural Flood Management at The Slade.'],
 ['Jul–Aug 2026','School car-park drain scheme paused','OCC paused the planned Courtington Lane / Workhouse Lane drain-line works because of concern over possible increased flooding elsewhere. Alternative solutions are being investigated.']
];

function renderProgramme(){
 const root=$('#programmeGrid'); if(root) root.innerHTML=programme.map(p=>`<article class="programme-card"><div class="programme-card-head"><div><p class="kicker">${safe(p.status)}</p><h3>${safe(p.title)}</h3></div><span class="status-pill"><i class="dot ${p.cls}"></i>${safe(p.status)}</span></div><dl class="programme-meta"><div><dt>Responsibility</dt><dd>${safe(p.lead)}</dd></div><div><dt>Funding</dt><dd>${safe(p.funding)}</dd></div><div><dt>Latest position</dt><dd>${safe(p.latest)}</dd></div></dl><ol class="mini-timeline">${p.dates.map(d=>`<li>${safe(d)}</li>`).join('')}</ol></article>`).join('');
 const hist=$('#historyTimeline'); if(hist) hist.innerHTML=milestones.map(([date,title,body])=>`<article><time>${safe(date)}</time><div><h3>${safe(title)}</h3><p>${safe(body)}</p></div></article>`).join('');
}

let map, mapMarkers={};
function initMap(){
 if(!window.L||!$('#bloxhamMap')) return;
 map=L.map('bloxhamMap',{scrollWheelZoom:false}).setView([52.02078,-1.3820],14);
 L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
 const add=(id,lat,lng,title,body)=>{const m=L.marker([lat,lng]).addTo(map).bindPopup(`<strong>${title}</strong><br>${body}`);mapMarkers[id]=m;};
 add('courtington',52.022884,-1.373615,'Courtington Lane / Workhouse Lane','Key drainage route. Section 19 work identified drainage restrictions and the proposed improvement scheme is currently paused while alternatives are assessed.');
 add('littlebridge',52.020868,-1.376290,'Little Bridge Road / Bloxham Brook','Brook crossing and local pinch-point area. Minor silt was cleared in 2025, but Storm Bert demonstrated the larger issue of channel and bridge capacity during extreme flow.');
 add('slade',52.0161,-1.3870,'The Slade Nature Reserve','Approximate centre based on the Parish Council reserve map. OCC-funded NFM work is being progressed here, including leaky dams / flow-spreading features.');
 add('tadmarton',52.024420,-1.395115,'Tadmarton Road / western catchment','A major surface-water pathway into Bloxham. The 2026 NFM study found that the principal surface-water contribution comes from west of the village towards Milcombe and along the Tadmarton Road catchment.');
 add('hobbhill',52.0271,-1.3836,'Hobb Hill — indicative area','Higher ground north-west of the village. Section 19 evidence described overland flow travelling south towards Courtington Lane. This marker is indicative, not a project boundary.');
 L.circle([52.024,-1.402],{radius:900,weight:2,fillOpacity:.08}).addTo(map).bindPopup('<strong>Western NFM opportunity area</strong><br>Indicative catchment area only. The Thames21 report assessed five participating land groups west of Bloxham; exact landowner boundaries are intentionally not shown.');
 $$('.map-key button').forEach(b=>b.addEventListener('click',()=>{const m=mapMarkers[b.dataset.mapTarget];if(m){map.setView(m.getLatLng(),16,{animate:true});m.openPopup();}}));
 setTimeout(()=>map.invalidateSize(),200);
}

async function load(){ $('#year').textContent=new Date().getFullYear(); renderProgramme(); initMap(); if(!db){fallback();return}
 const {data:c}=await db.from('site_content').select('*').eq('id',1).maybeSingle(); if(c){$('#status').textContent=c.status||'Updates ongoing';$('#updated').textContent=c.updated||'—';$('#focus').textContent=c.focus||'—';$('#intro').textContent=c.intro||$('#intro').textContent;$('#latest').textContent=c.latest||'Further updates will appear here.'}
 const {data:ps}=await db.from('projects').select('*').eq('published',true).order('sort_order'); $('#projectsGrid').innerHTML=(ps||[]).map(p=>{const [label,cls]=statusInfo(p);return `<article class="project-card"><div class="project-top"><span class="project-icon">${safe(p.icon||'🌊')}</span><span class="status-pill"><i class="dot ${cls}"></i> ${label}</span></div><h3>${safe(p.title)}</h3><p>${safe(p.description)}</p><div class="project-meta">See detailed tracker below</div></article>`}).join('')||'<p class="muted">Project information is being prepared.</p>';
 const {data:docs}=await db.from('documents').select('*').eq('published',true).order('created_at',{ascending:false}).limit(4); $('#documents').innerHTML=(docs||[]).map(d=>`<p><a href="${safe(d.url)}" target="_blank" rel="noopener">${safe(d.title)} →</a></p>`).join('')||'<p class="muted">Document links will be added here.</p>';
 const {data:qs}=await db.from('questions').select('id,name,type,body,answer,created_at').eq('published',true).order('created_at',{ascending:false}).limit(6); $('#published').innerHTML=(qs||[]).map(q=>`<article class="question-card"><small>${safe(q.type)} · ${safe(q.name)}</small><p>${safe(q.body)}</p>${q.answer?`<p class="answer"><b>Response:</b> ${safe(q.answer)}</p>`:''}</article>`).join('')||'<p class="muted">Published community questions will appear here.</p>';
}
function fallback(){$('#status').textContent='Flood alleviation programme active';$('#updated').textContent='August 2026';$('#focus').textContent='The Slade NFM; Courtington / Workhouse alternatives; wider catchment NFM';$('#latest').textContent='OCC grant funding for Natural Flood Management at The Slade has been approved / is being released, while the planned drain-line works beneath Bloxham School car park remain paused and alternative solutions are being investigated.';$('#projectsGrid').innerHTML='<article class="project-card"><div class="project-top"><span class="project-icon">🌿</span><span class="status-pill"><i class="dot progress"></i> In progress</span></div><h3>The Slade</h3><p>OCC-funded Natural Flood Management measures, including leaky dams / flow spreading, are being progressed.</p></article><article class="project-card"><div class="project-top"><span class="project-icon">🚧</span><span class="status-pill"><i class="dot delayed"></i> Paused</span></div><h3>Courtington Lane / Workhouse Lane</h3><p>The original drain-line scheme is paused while alternative solutions and downstream impacts are investigated.</p></article><article class="project-card"><div class="project-top"><span class="project-icon">🌧️</span><span class="status-pill"><i class="dot investigation"></i> Design / funding</span></div><h3>Western catchment NFM</h3><p>The 2026 feasibility report identifies storage ponds, field-corner bunds and leaky dams across participating land groups.</p></article>';$('#documents').innerHTML='<p class="muted">Documents will appear here.</p>';$('#published').innerHTML='<p class="muted">Published community questions will appear here.</p>'}
const form=$('#questionForm');form?.addEventListener('submit',async e=>{e.preventDefault();const msg=$('#formMessage');if(!db){msg.textContent='Submissions are temporarily unavailable.';return}const f=new FormData(form);msg.textContent='Sending…';const {error}=await db.from('questions').insert({name:f.get('name'),email:f.get('email'),type:f.get('type'),body:f.get('body'),published:false});msg.textContent=error?'Sorry — your message could not be sent. Please try again.':'Thank you. Your message has been sent for moderation.';if(!error)form.reset()});
$('.menu')?.addEventListener('click',()=>{const n=$('.nav nav');n.style.display=n.style.display==='flex'?'none':'flex';n.style.position='absolute';n.style.top='76px';n.style.left='0';n.style.right='0';n.style.padding='18px 5%';n.style.background='#0c2e39';n.style.flexDirection='column'});
load();